---

- name: apt upgrade
  become: true
  apt:
    name: unattended-upgrades
    state: present
    install_recommends: no
  when: system_apt_auto_upgrade|bool
  tags: ['system']

- name: Apt auto-upgrade default
  become: true
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  when: system_apt_auto_upgrade|bool
  with_items:
    - { src: 'apt_auto_upgrades.j2',        dest: '/etc/apt/apt.conf.d/20auto-upgrades' }
    - { src: 'apt_unattended_upgrades.j2',  dest: '/etc/apt/apt.conf.d/90unattended-upgrades' }
  tags: ['system']

- name: Disable Unattended Upgrades Shutdown service
  become: true
  service:
    name: unattended-upgrades
    state: stopped
    enabled: no
  when: system_apt_auto_upgrade|bool
  tags: ['system']
