---

- name: package cpufrequtils
  apt:
    name: cpufrequtils
  become: yes

- name: cpufrequtils
  template:
    src: cpufrequtils.j2
    dest: /etc/default/cpufrequtils
  when: not (ansible_virtualization_role is defined and ansible_virtualization_role != "host")
  become: yes
