---

# - name: Set Hostname with hostname command
#   hostname: name="{{ server_hostname|default(inventory_hostname) }}"
#   when: not (ansible_virtualization_role == "guest" and ansible_virtualization_type == "lxc")
#   ignore_errors: yes
#   become: yes

- name: replace network config
  template:
    src: "{{ system_network_interface }}"
    dest: /etc/network/interfaces
  when: system_network|bool and ansible_os_family == "Debian"
  become: yes

- name: Ensure folder exist
  file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  when: ansible_os_family == "Debian"
  with_items:
    - /etc/systemd/network
    - /etc/systemd/system/networking.service.d
  become: yes

- name: reduce timeout raise network
  template:
    src: interfaces-timeout.conf.j2
    dest: /etc/systemd/system/networking.service.d/interfaces-timeout.conf
  when: ansible_os_family == "Debian" and ansible_service_mgr == 'systemd'
  become: yes

- name: pin network interface name
  template:
    src: interfaces-persistent-net.j2
    dest: /etc/systemd/network/10-persistent-net-eth0.link
  when: ansible_os_family == "Debian" and system_network_pin and ansible_service_mgr == 'systemd'
  become: yes

- name: configure dummy interface
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  when: ansible_os_family == "Debian" and system_network_dummy_ip and system_network_dummy_ip != ''
  with_items:
    - { src: dummy.conf.j2,       dest: /etc/modprobe.d/dummy.conf }
  become: yes
