---

- include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_distribution_release }}.yml"
    - "../vars/{{ ansible_os_family }}.yml"
    - "../vars/empty.yml"
  tags: ['system','network']

- name: set root password
  user:
    name: root
    password: "{{ system_root_password }}"
  when: system_root_password is defined and system_root_password
  tags: ['system']

- name: update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 86400
  when: ansible_os_family == "Debian"
  become: yes
  tags: ['system']

- name: packages (debian)
  apt:
    name: '{{ system_packages }}'
  become: yes
  when: ansible_os_family == "Debian"
  tags: ['system']

- name: packages (centos)
  yum:
    name: '{{ system_packages }}'
  become: yes
  when: ansible_os_family == "RedHat"
  tags: ['system']

- file:
    path: '{{ item.path }}'
    state: directory
    mode: '{{ item.mode }}'
  with_items:
    - { path: /etc/vim,     mode: '0755' }
    - { path: /root/bin,    mode: '0755' }
    - { path: /root/.ssh,   mode: '0700' }
  become: yes
  tags: ['system']

### Need fix (ansible bugs)
- name: set
  locale_gen:
    name: en_US.UTF-8
    state: present
  ignore_errors: yes
  register: change_locale
  when: ansible_os_family == "Debian"
  become: yes
  tags: ['system']

- name: Create the locale
  become: yes
  command: /usr/sbin/locale-gen en_US.UTF-8
  when: ansible_os_family == "Debian" and change_locale.changed
  tags: ['system']

- name: Set the locale by default
  become: yes
  command: /usr/sbin/update-locale LANG=en_US.UTF-8 --reset
  when: ansible_os_family == "Debian" and change_locale.changed
  tags: ['system']
###

- file:
    path: /etc/rc.d/rc.local
    mode: 0755
  when: ansible_os_family == "RedHat"
  become: yes
  tags: ['system']

- import_tasks: time.yml
- import_tasks: apt.yml
  when: ansible_os_family == "Debian"

- import_tasks: yum.yml
  when: ansible_os_family == "RedHat"

- import_tasks: security.yml
- import_tasks: sysctl.yml
- import_tasks: grub.yml
  when: ansible_virtualization_role is defined and
        not (ansible_virtualization_role == "guest" and ansible_virtualization_type == "lxc")

- import_tasks: cpufrequtils.yml
  when: system_cpufrequtils_governor is defined and system_cpufrequtils_governor

- import_tasks: postfix.yml
  when: system_postfix|bool

- import_tasks: hostname.yml
  when: system_network|bool

- import_tasks: resolv.yml
- import_tasks: interface.yml
  when: system_network|bool
